Rails.application.routes.draw do
  get 'products/index'
  get 'products/show'
  get 'products/create'
  get 'products/show'
  get 'products/update'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'synonyms/new'
  get 'synonyms/create'
  get 'synonyms/show'
  get 'synonyms/update'
  get 'variants/new'
  get 'variants/create'
  get 'variants/update'
  get 'variants/destroy'
  get 'compositions/index'
  get 'compositions/show'
  get 'ratings/create'
  get 'orders/index'
  get 'orders/create'
  get 'orders/show'
  get 'profiles/new'
  get 'profiles/create'
  get 'profiles/show'
  get 'profiles/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
